version: '3'

services:
  "criticalmiss_webservice_data":
    image: "criticalmiss-webservice-data"
    build:
      context: .
      dockerfile: CriticalMiss.WebService.Data/Dockerfile
#    deploy:
#      replicas: 1
    networks:
      - critmiss

  "criticalmiss_ui":
    image: "criticalmiss-ui"
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: CriticalMiss.UI/Dockerfile
    ports: 
      - "80:5000"
    networks:
      - critmiss

  "criticalmiss_webservice_library":
    image: "criticalmiss-webservice-library"
    deploy:
#      replicas: 1
    build:
      context: .
      dockerfile: CriticalMiss.WebService.Library/Dockerfile
    networks:
      - critmiss

networks:
  critmiss: