node('master') {
    stage('import') {
        try {
            git url:'https://github.com/TabletopDream/CriticalMiss.git'
        } catch {
            //slacksend message:{env.BUILD_NUMBER}  color:'danger'
        }
    }
    
    stage('build') {
        try {

        } catch {
            //slacksend message: color:'danger'
        }
    }

    stage('analyze') {
        try {

        } catch {
            //slacksend message: color:'danger'
        }
    }

    stage('test') {
        try {

        } catch {
            //slacksend message: color:'danger'
        }
    }

    stage('package') {
        try {

        } catch {
            //slacksend message: color:'danger'
        }
    }

    stage('deploy') {
        try {

        } catch {
            //slacksend message: color:'danger'
        }
    }
}