version: '3'

services:
  "criticalmiss_angular":
    image: "ajhl49/criticalmiss-angular"
    build:
      context: ./CriticalMissNg
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - critmiss
    ports:
      - "80:80"
  
  "criticalmiss_webservice_data":
    image: "ajhl49/criticalmiss-webservice-data"
    build:
      context: ./CriticalMiss
      dockerfile: CriticalMiss.WebService.Data/Dockerfile
#    deploy:
#      replicas: 1
    networks:
      - critmiss

  "criticalmiss_ui":
    image: "ajhl49/criticalmiss-ui"
    deploy:
      replicas: 1
    build:
      context: ./CriticalMiss
      dockerfile: CriticalMiss.UI/Dockerfile
    networks:
      - critmiss

  "criticalmiss_webservice_library":
    image: "ajhl49/criticalmiss-webservice-library"
    deploy:
      replicas: 1
    build:
      context: ./CriticalMiss
      dockerfile: CriticalMiss.WebService.Library/Dockerfile
    networks:
      - critmiss

networks:
  critmiss: